# SPDX-FileCopyrightText: 2024 Gergely Horváth
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Label Studio systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ labelstudio_identifier }}.service"
  register: labelstudio_service_stat

- when: labelstudio_service_stat.stat.exists | bool
  block:
    - name: Ensure Label Studio systemd service is stopped
      ansible.builtin.service:
        name: "{{ labelstudio_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Label Studio systemd service does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ devture_systemd_docker_base_systemd_path }}/{{ labelstudio_identifier }}.service"

    - name: Ensure Label Studio path doesn't exist
      ansible.builtin.file:
        path: "{{ labelstudio_base_path }}"
        state: absent
