# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Gergely Horváth
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "labelstudio_http_header_content_permission_policy", "new": "labelstudio_http_header_permissions_policy" }
    - { "old": "labelstudio_systemd_required_systemd_services_list", "new": "labelstudio_systemd_required_services_list" }
    - { "old": "labelstudio_systemd_required_systemd_services_list_default", "new": "labelstudio_systemd_required_services_list_default" }
    - { "old": "labelstudio_systemd_required_systemd_services_list_auto", "new": "labelstudio_systemd_required_services_list_auto" }
    - { "old": "labelstudio_systemd_required_systemd_services_list_custom", "new": "labelstudio_systemd_required_services_list_custom" }
    - { "old": "labelstudio_container_image_force_pull", "new": "<removed> (the new community.docker.docker_image_pull module handles this natively)" }

- name: Fail if required Label Studio settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - {'name': 'labelstudio_identifier', when: true}
    - {'name': 'labelstudio_uid', when: true}
    - {'name': 'labelstudio_gid', when: true}
    - {'name': 'labelstudio_hostname', when: true}
    - {'name': 'labelstudio_path_prefix', when: true}
    - {'name': 'labelstudio_container_network', when: true}
    - {'name': 'labelstudio_container_labels_traefik_compression_middleware_name', when: "{{ labelstudio_container_labels_traefik_compression_middleware_enabled }}"}
    - {'name': 'labelstudio_database_name', when: "{{ labelstudio_postgres_backend_enabled }}"}
    - {'name': 'labelstudio_database_username', when: "{{ labelstudio_postgres_backend_enabled }}"}
    - {'name': 'labelstudio_database_password', when: "{{ labelstudio_postgres_backend_enabled }}"}
    - {'name': 'labelstudio_database_port', when: "{{ labelstudio_postgres_backend_enabled }}"}
    - {'name': 'labelstudio_database_hostname', when: "{{ labelstudio_postgres_backend_enabled }}"}
    - {'name': 'labelstudio_environment_variables_minio_root_user', when: "{{ labelstudio_minio_backend_enabled }}"}
    - {'name': 'labelstudio_environment_variables_minio_root_password', when: "{{ labelstudio_minio_backend_enabled }}"}
    - {'name': 'labelstudio_environment_variables_username', when: "{{ labelstudio_environment_variables_disable_signup_without_link }}"}
    - {'name': 'labelstudio_environment_variables_password', when: "{{ labelstudio_environment_variables_disable_signup_without_link }}"}

- name: Run if Traefik is enabled
  when: labelstudio_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Label Studio are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - labelstudio_container_labels_traefik_hostname
        - labelstudio_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `labelstudio_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if labelstudio_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          labelstudio_container_labels_traefik_path_prefix (`{{ labelstudio_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/labelstudio`).
      when: "labelstudio_container_labels_traefik_path_prefix != '/' and labelstudio_container_labels_traefik_path_prefix[-1] == '/'"
